# Generated by Django 5.2.8 on 2025-11-15 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0002_alter_stockbatch_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='reorder_level',
            field=models.IntegerField(default=0, help_text='The minimum stock level before a reorder is triggered.'),
        ),
    ]
